# Generated by Django 3.1.4 on 2020-12-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201223_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
