# Generated by Django 3.1.4 on 2020-12-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201228_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='timeStamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
