# Generated by Django 3.1.4 on 2020-12-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201228_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postblog',
            old_name='timeStamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='postblog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
